### ISSUE TITLE
Version conflict between dependency declaration (AWSSDK.DynamoDBv2) and latest AWS SDK .Net

### ISSUE THREAD

**Issue by jaimeimarin** [aws/aws-dotnet-session-provider#19]
## Description
Please review this previous bug report: https://github.com/aws/aws-dotnet-session-provider/issues/5

The same behavior is happening but with the new latest version.

Since AWS SDK v.3.5.0.9 has been released I can't use latest version of AWS.SessionProvider anymore due to dependency conflict.

### Environment
* OS Info: Windows 10
* Build Environment: Visual Studio Community Edition 2019
* Targeted .NET Platform: 
- .Net 4.7.2
- AWS SDK for .NET: SessionProvider 3.3.0
- Dependencies: AWSSDK.DynamoDBv2 (>= 3.3.4 && < 3.4.0)

## Reproduction Steps
* Go to the solution explorer
* Right-click on desired project
* Go to 'Manage Nuget Packages'
* Click on 'Update'

### Logs
Unable to find a version of 'AWSSDK.DynamoDBv2' that is compatible with 'AWS.SessionProvider 3.3.0 constraint: AWSSDK.DynamoDBv2 (>= 3.3.4 && < 3.4.0)'.				

## Resolution
Does it compatible with Core v3.5.0.9? Could you update dependencies restrictions accordingly?

**Comment by ashishdhingra** [comment]
Hi @jaimeimarin,

Thanks for reporting the issue. I will discuss the issue with the development team and post any update here accordingly.

Regards,
Ashish

**Comment by Beggel** [comment]
Hi @ashishdhingra ,
The same issue. I am trying to update AWSSDK.Core package to version 3.5.1.9. This is required to update AWSSDK.DynamoDBv2 package at least to version 3.5.0.9. But due to error it is impossible: "Unable to resolve dependencies. 'AWSSDK.DynamoDBv2 3.5.0.9' is not compatible with 'AWS.SessionProvider 3.3.0 constraint: AWSSDK.DynamoDBv2 (>= 3.3.4 && < 3.4.0)'"

**Comment by ashovlin** [comment]
This should be resolved in version 4.0 which was released on 11/6/2020. Thanks.
